### ISSUE TITLE
multi_style_warp, alpha, and patch_size

### ISSUE THREAD

**Issue by thortower** [zxhuang97/Official-implementation-StyleMixer#1]
Hello,

I've enjoyed reading your paper and was very happy to find your github implementation of it. I'm just playing around with some results and noticed some issues. 

It seems there are two multi_style_warp functions defined in kmeans.py. The one that is used doesn't accept a patch_size and doesn't do anything with the alpha parameter. The other function throws an error due to a tuple being passed instead of a tensor. I'd like to be able to play with alpha's, cluster's, and patches to see how they affect the output.

Is this something you plan on fixing? I can look into fixing and submitting a PR, if you'd be willing to give me some guidance on your thought process for this piece.

Thanks and I appreciate your work!

**Comment by zxhuang97** [comment]
@thortower Thank you so much for your suggestion. Actually the codebase is not fully prepared at the moment. We are still cleaning up the unused api. 
We will consider your suggestion of adding alpha and patch_size control in our next version(a few days later).
A simple version of alpha implementation could be done by output = (1-alpha)*content + alpha*style  in Nonlocal.Fusion.
For the patch_size, it's not a runtime control, which means you need to retrain the model if you want to play with patch_size other than 3.

**Comment by thortower** [comment]
Thank you for your help!

**Comment by zxhuang97** [comment]
@thortower The codes are prepared now.  Please feel free to check it out.
