### ISSUE TITLE
pretrained model download

### ISSUE THREAD

**Issue by huanghsheng** [zxhuang97/Official-implementation-StyleMixer#3]
Dear author, thanks for your amazing work and contribution. However, the pretrained model cannot be downloaded by the script nor the link, and the downloaded tar files cannot be extracted. Is the uploaded file broken?

**Comment by chschere** [comment]
You can download the pretrained vgg from here as well I guess: https://github.com/GlebBrykin/SANET.
For me, the other model worked via the link and did not need extracting.

**Comment by zxhuang97** [comment]
Hi,

You don't need to extract the model checkpoint. Directly loading it with torch should work. Thanks.

**Comment by zxhuang97** [comment]
Issue solved
